### ISSUE TITLE
BIOS patched or factory?

### ISSUE THREAD

**Issue by mandurphy** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur#10]
The bios file you have linked here, is this one of AsRock’s beta bios files on their website or is it a patched bios file? If it’s factory, On the asrock website, the beta bios files are up to 4.40H. Does this offer the same TB3 support as the one linked here?

**Comment by seanzhang98** [comment]
This is factory bios but not avalible on thier website, not sure if 4.40H will work but you can always give it a try

**Comment by seanzhang98** [comment]
Just tried 4.40H, No TB3 support and TB3 function not working.
