### ISSUE TITLE
提示OCS信息

### ISSUE THREAD

**Issue by lylala8** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur#11]
EFI放好后，开机 提示OCS：NO scheam for keymergethreshold at 2 index, context<input>!
halting on critical error 

希望作者能给点提示 感谢

**Comment by TypeVII** [comment]
把这个在config.plist 删除掉就可以，OC0.6.7 不需要这个

**Comment by lylala8** [comment]
> 把这个在config.plist 删除掉就可以，OC0.6.7 不需要这个

删除后只提示这个
halting on critical error

我按照文档选了机型重新开机引导 又报错 这次更多了
OCS: no schema for bootprotect at 4 index,context
ocs:failed to calculate size of false field containg<empty> as type integer,context<playchime>!
ocs: no schema for deduplicatebootorder at 0 index,context
halting on critical error

**Comment by TypeVII** [comment]
nvram 清空没有， 多清几次，主板也是asrock z390 Phantom ITX 吗？ 如果还是不行我分享给你我的，我也是改了sean的配置才能用的

**Comment by lylala8** [comment]
是的   用的这个efi 启动不了 ，不知道啥原因 ，看到你的仓库里有个EFI 是您现在用的吗
能提供给我试试吗

**Comment by lylala8** [comment]
我没有显卡
cpu是8700 用的核显 
网卡是原装的  inter网卡是可以驱动了吗
引导进不去是否跟这些有关系

**Comment by lylala8** [comment]
老哥给个信息吧

**Comment by seanzhang98** [comment]
看官方文档针对报错修改，更新OC要根据更新内容修改config
