### ISSUE TITLE
刷完BIOS 4.40c后，thunderbolt 3仍然无法激活

### ISSUE THREAD

**Issue by ansonliao** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur#2]
@seanzhang98 
谢谢你详细的教程！
我刷完BIOS 4.40c后，thunderbolt 3仍然无法激活，请问需要什么操作？
macOS: 10.15.7

谢谢！

**Comment by seanzhang98** [comment]
@ansonliao 你bios里面的设置按教程开了吗？

**Comment by ansonliao** [comment]
@seanzhang98 

是的，BIOS按照你的教程设置好了。

**Comment by seanzhang98** [comment]
@ansonliao 检查一下 config 的 patch 的 change _E2C to XE2C for TB hotplug 有没有开启，再不行清一下 nvram 或者重新刷一下 bios。可以参考一下 [华擎ASRock Z390 Phantom Gaming ITX/ac 雷电3 完美驱动 热插拔](http://blog.fangf.cc/2020/05/19/TB3/)

**Comment by seanzhang98** [comment]
@ansonliao 你需要的 ssdt 可能是 SSDT-TbtOnPch_PINI_D8.aml 而不是我现在 EFI 带的 SSDT-TbtOnPch_PINI.aml

**Comment by ansonliao** [comment]
@seanzhang98 
好的，我试试

**Comment by ansonliao** [comment]
@seanzhang98 
请问还要在windows下刷thunderbolt 3的驱动的么？
加了`SSDT-TbtOnPch_PINI.aml`，`SSDT-DTPG.aml`和ACPI的patch后还是不行 (我的是pini.aml这个类型)

**Comment by seanzhang98** [comment]
@ansonliao 如果还不行就升级一下

**Comment by ansonliao** [comment]
@seanzhang98 
那就不行了，老房的教程很早就看过了，一直没操作，因为手上没有Windows电脑。
谢谢你的回复。

**Comment by ansonliao** [comment]
@seanzhang98 
在windows 下面刷了TB3的固件，加入指定的SSDT和PATCH，成功开启TB3，谢谢。
