### ISSUE TITLE
Windows 死机

### ISSUE THREAD

**Issue by Tanrky** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur#3]
你好，最近采用了你的 EFI 文件进行了修改，macOS 使用没有问题，但是 Windows 在 bios 引导后容易出现卡死的情况，而拔出 装有 macOS 的 SSD 就正常了，不知道你是否有遇到类似的问题呢？

**Comment by seanzhang98** [comment]
正常，OC默认所以系统都应用 ACPI 补丁，用主板自带的引导就好了。
