### ISSUE TITLE
WIFI-BLUETOOTH DOESN'T WORK

### ISSUE THREAD

**Issue by LUTHERO** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur#5]
Follow your guide step by step, bought wifi module BCM94360CS2 and installed, but doesn't work...

**Comment by seanzhang98** [comment]
To make sure your module is working (can be detected and recognized under Windows.) and the usb mapping for ```HS14``` is set as ```Internal```. It should works if it was correctly installed and functional.
