### ISSUE TITLE
相同配置，开机提示halting on critical error，可能会是什么问题？

### ISSUE THREAD

**Issue by raymond2010** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur#6]
相同配置，开机提示halting on critical error，可能会是什么问题？

**Comment by AaronZYHK** [comment]
遇到了同样的情况 如果换成0.62版的first release 好歹能正常引导 0.66版直接就是halting on critical error。

**Comment by raymond2010** [comment]
@seanzhang98 请问是否还在更新？我看OC0.6.7已经发布了

**Comment by seanzhang98** [comment]
@raymond2010 自行更新就好，最近比较繁忙暂时没时间更新

**Comment by titianqx** [comment]
我也遇到这个情况了 用别的EFI没什么问题  但是别的没有雷雳..  @raymond2010  请问怎么解决的

**Comment by lylala8** [comment]
@raymond2010  我也是oc 提示这个 请问你解决了吗

**Comment by htchaan** [comment]
其實可以留著不closed等有綠人的
