### ISSUE TITLE
请问作者遇到了刷雷电3BIOS导致显卡接口降速为PCIE8x么？

### ISSUE THREAD

**Issue by desert0616** [seanzhang98/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh-BigSur#7]
如题，谢谢。

**Comment by seanzhang98** [comment]
本人的设备没有遇到，从GPU-Z确认到显卡是运行在PCIE 3.0 X16的速度上的

**Comment by desert0616** [comment]
在mac下的system report里，gpu的PCIe Lane Width 也汇报为16x？

**Comment by seanzhang98** [comment]
@desert0616 是的
<img width="1097" alt="EA5A858A-F8EA-4C49-8E4A-2849A5127E27" src="https://user-images.githubusercontent.com/34902361/114652945-840b2c00-9d19-11eb-8d0d-08de84fd3c68.png">
